### ISSUE TITLE
ICDPred score unable to be calculated

### ISSUE THREAD

**Issue by TDorado7** [kroemerlab/ICDpred#2]
Hello, I came across the ICDPred package after seeing the manuscript in EMBO Molecular Medicine (EMBO Mol Med (2020)12:e11622). I installed it into R following the directions on GitHub and tried scoring the compounds shown in Figure 1 to verify I had installed it correctly. I was able to match the ICD prediction scores for mitoxantrone and 5-fluorodeoxycytidine but was unable to calculate a score for the rest of the compounds in the figure. Upon closer observation, I saw that in the ‘Descriptors’ section, the value for ‘constitutional.nAtomLAC’ would return as “NA” for compounds that were unable to be scored. I believe the “NA” value may be prohibiting the rest of the calculation. Is there a way to correct this issue?

**Comment by asauvat** [comment]
Hello, thanks for reporting the error with such details. I was able to reproduce the error by updating rcdk; it seems indeed that the new package version generates NAs when computing the ‘constitutional.nAtomLAC’ descriptor, thus making the calculation impossible. A quick workaround was to replace the 'NA' value  by the median from the training set, which seems to give equivalent results. I will update the package accordingly while waiting for a more viable fix.
